version: "3.8"

services:
  chatbot:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - db
      - chroma

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: password
      POSTGRES_DB: unahur_chatbot
    ports:
      - "5432:5432"

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8000:8000"